# vim:ft=kitty
#
font_family CaskaydiaCove NFM Regular
font_size   10.0
modify_font cell_height 150%

disable_ligatures always

font_features CaskaydiaCoveNFM-Regular -calt +ss01

window_padding_width 3 2

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
